<?php

declare(strict_types=1);

namespace Kyzegs\Laracord\Endpoints;

use Kyzegs\Laracord\Enums\AuthenticationRequirement;
use Kyzegs\Laracord\Enums\HttpMethod;

/** Generated from Laracord 0.x route surface; edit through endpoint audit tooling. */
final class GeneratedEndpointDefinitions
{
    /** @return array<string, array<string, array{method:HttpMethod,path:string,auth?:AuthenticationRequirement,form?:bool}>> */
    public static function all(): array
    {
        return [
            'applications' => [
                'getCurrentApplication' => ['method' => HttpMethod::Get, 'path' => '/applications/@me'],
            ],
            'auditLogs' => [
                'getGuildAuditLog' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/audit-logs'],
            ],
            'autoModeration' => [
                'listAutoModerationRulesForGuild' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/auto-moderation/rules'],
                'getAutoModerationRule' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/auto-moderation/rules/{auto_moderation_rule_id}'],
                'createAutoModerationRule' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/auto-moderation/rules'],
                'modifyAutoModerationRule' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/auto-moderation/rules/{auto_moderation_rule_id}'],
                'deleteAutoModerationRule' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/auto-moderation/rules/{auto_moderation_rule_id}'],
            ],
            'channels' => [
                'getChannel' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}'],
                'modifyChannel' => ['method' => HttpMethod::Patch, 'path' => '/channels/{channel_id}'],
                'deleteChannel' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}'],
                'editChannelPermissions' => ['method' => HttpMethod::Put, 'path' => '/channels/{channel_id}/permissions/{overwrite_id}'],
                'deleteChannelPermission' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/permissions/{overwrite_id}'],
                'followAnnouncementChannel' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/followers'],
                'triggerTypingIndicator' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/typing'],
                'getPinnedMessages' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/pins'],
                'pinMessage' => ['method' => HttpMethod::Put, 'path' => '/channels/{channel_id}/pins/{message_id}'],
                'unpinMessage' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/pins/{message_id}'],
                'startThreadWithoutMessage' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/threads'],
                'startThreadInForumChannel' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/threads'],
                'joinThread' => ['method' => HttpMethod::Put, 'path' => '/channels/{channel_id}/thread-members/@me'],
                'addThreadMember' => ['method' => HttpMethod::Put, 'path' => '/channels/{channel_id}/thread-members/{user_id}'],
                'leaveThread' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/thread-members/@me'],
                'removeThreadMember' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/thread-members/{user_id}'],
                'getThreadMember' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/thread-members/{user_id}'],
                'listThreadMembers' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/thread-members'],
                'listPublicArchivedThreads' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/threads/archived/public'],
                'listPrivateArchivedThreads' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/threads/archived/private'],
                'listJoinedPrivateArchivedThreads' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/users/@me/threads/archived/private'],
            ],
            'commands' => [
                'getGlobalApplicationCommands' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/commands'],
                'createGlobalApplicationCommand' => ['method' => HttpMethod::Post, 'path' => '/applications/{application_id}/commands'],
                'getGlobalApplicationCommand' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/commands/{command_id}'],
                'editGlobalApplicationCommand' => ['method' => HttpMethod::Patch, 'path' => '/applications/{application_id}/commands/{command_id}'],
                'deleteGlobalApplicationCommand' => ['method' => HttpMethod::Delete, 'path' => '/applications/{application_id}/commands/{command_id}'],
                'bulkOverwriteGlobalApplicationCommands' => ['method' => HttpMethod::Put, 'path' => '/applications/{application_id}/commands'],
                'getGuildApplicationCommands' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands'],
                'createGuildApplicationCommand' => ['method' => HttpMethod::Post, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands'],
                'getGuildApplicationCommand' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/{command_id}'],
                'editGuildApplicationCommand' => ['method' => HttpMethod::Patch, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/{command_id}'],
                'deleteGuildApplicationCommand' => ['method' => HttpMethod::Delete, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/{command_id}'],
                'bulkOverwriteGuildApplicationCommands' => ['method' => HttpMethod::Put, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands'],
                'getGuildApplicationCommandPermissions' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/permissions'],
                'getApplicationCommandPermissions' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions'],
                'editApplicationCommandPermissions' => ['method' => HttpMethod::Put, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions'],
                'batchEditApplicationCommandPermissions' => ['method' => HttpMethod::Put, 'path' => '/applications/{application_id}/guilds/{guild_id}/commands/permissions'],
            ],
            'emojis' => [
                'listGuildEmojis' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/emojis'],
                'getGuildEmoji' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/emojis/{emoji_id}'],
                'createGuildEmoji' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/emojis'],
                'modifyGuildEmoji' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/emojis/{emoji_id}'],
                'deleteGuildEmoji' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/emojis/{emoji_id}'],
            ],
            'guilds' => [
                'createGuild' => ['method' => HttpMethod::Post, 'path' => '/guilds'],
                'getGuild' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}'],
                'getGuildPreview' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/preview'],
                'modifyGuild' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}'],
                'deleteGuild' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}'],
                'getGuildChannels' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/channels'],
                'createGuildChannel' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/channels'],
                'modifyGuildChannelPositions' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/channels'],
                'listActiveGuildThreads' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/threads/active'],
                'getGuildMember' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/members/{user_id}'],
                'listGuildMembers' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/members'],
                'searchGuildMembers' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/members/search'],
                'addGuildMember' => ['method' => HttpMethod::Put, 'path' => '/guilds/{guild_id}/members/{user_id}'],
                'modifyGuildMember' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/members/{user_id}'],
                'modifyCurrentMember' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/members/@me'],
                'addGuildMemberRole' => ['method' => HttpMethod::Put, 'path' => '/guilds/{guild_id}/members/{user_id}/roles/{role_id}'],
                'removeGuildMemberRole' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/members/{user_id}/roles/{role_id}'],
                'removeGuildMember' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/members/{user_id}'],
                'getGuildBans' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/bans'],
                'getGuildBan' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/bans/{user_id}'],
                'createGuildBan' => ['method' => HttpMethod::Put, 'path' => '/guilds/{guild_id}/bans/{user_id}'],
                'removeGuildBan' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/bans/{user_id}'],
                'getGuildRoles' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/roles'],
                'createGuildRole' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/roles'],
                'modifyGuildRolePositions' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/roles'],
                'modifyGuildRole' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/roles/{role_id}'],
                'modifyGuildMfaLevel' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/mfa'],
                'deleteGuildRole' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/roles/{role_id}'],
                'getGuildPruneCount' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/prune'],
                'beginGuildPrune' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/prune'],
                'getGuildIntegrations' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/integrations'],
                'deleteGuildIntegrations' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/integrations/{integration_id}'],
                'getGuildWidgetSettings' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/widget'],
                'modifyGuildWidget' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/widget'],
                'getGuildWidget' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/widget.json'],
                'getGuildVanityUrl' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/vanity-url'],
                'getGuildWidgetImage' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/widget.png'],
                'getGuildWelcomeScreen' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/welcome-screen'],
                'modifyGuildWelcomeScreen' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/welcome-screen'],
                'getGuildOnboarding' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/onboarding'],
                'modifyGuildOnboarding' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/onboarding'],
            ],
            'invites' => [
                'getChannelInvites' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/invites'],
                'createChannelInvite' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/invites'],
                'getGuildInvites' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/invites'],
                'getInvite' => ['method' => HttpMethod::Get, 'path' => '/invites/{invite_code}'],
                'deleteInvite' => ['method' => HttpMethod::Delete, 'path' => '/invites/{invite_code}'],
            ],
            'messages' => [
                'getChannelMessages' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/messages'],
                'getChannelMessage' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/messages/{message_id}'],
                'createMessage' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/messages'],
                'crosspostMessage' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/messages/{message_id}/crosspost'],
                'createReaction' => ['method' => HttpMethod::Put, 'path' => '/channels/{channel_id}/messages/{message_id}/reactions/{emoji}/@me'],
                'deleteOwnReaction' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/messages/{message_id}/reactions/{emoji}/@me'],
                'deleteUserReaction' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/messages/{message_id}/reactions/{emoji}/{user_id}'],
                'getReactions' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/messages/{message_id}/reactions/{emoji}'],
                'deleteAllReactions' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/messages/{message_id}/reactions'],
                'deleteAllReactionsForEmoji' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/messages/{message_id}/reactions/{emoji}'],
                'editMessage' => ['method' => HttpMethod::Patch, 'path' => '/channels/{channel_id}/messages/{message_id}'],
                'deleteMessage' => ['method' => HttpMethod::Delete, 'path' => '/channels/{channel_id}/messages/{message_id}'],
                'bulkDeleteMessages' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/messages/bulk-delete'],
                'startThreadFromMessage' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/messages/{message_id}/threads'],
                'getWebhookMessage' => ['method' => HttpMethod::Get, 'path' => '/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}', 'auth' => AuthenticationRequirement::None],
                'editWebhookMessage' => ['method' => HttpMethod::Patch, 'path' => '/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}', 'auth' => AuthenticationRequirement::None],
                'deleteWebhookMessage' => ['method' => HttpMethod::Delete, 'path' => '/webhooks/{webhook_id}/{webhook_token}/messages/{message_id}', 'auth' => AuthenticationRequirement::None],
            ],
            'roleConnections' => [
                'getApplicationRoleConnectionMetadataRecords' => ['method' => HttpMethod::Get, 'path' => '/applications/{application_id}/role-connections/metadata'],
                'updateApplicationRoleConnectionMetadataRecords' => ['method' => HttpMethod::Put, 'path' => '/applications/{application_id}/role-connections/metadata'],
                'getUserApplicationRoleConnections' => ['method' => HttpMethod::Get, 'path' => '/users/@me/connections/{guild_id}'],
                'updateUserApplicationRoleConnections' => ['method' => HttpMethod::Patch, 'path' => '/users/@me/connections/{guild_id}'],
            ],
            'scheduledEvents' => [
                'listScheduledEventsForGuild' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/events'],
                'createGuildScheduledEvent' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/events'],
                'getGuildScheduledEvent' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/events/{guild_scheduled_event_id}'],
                'modifyGuildScheduledEvent' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/events/{guild_scheduled_event_id}'],
                'deleteGuildScheduledEvent' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/events/{guild_scheduled_event_id}'],
                'getGuildScheduledEventUsers' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/events/{guild_scheduled_event_id}/users'],
            ],
            'stages' => [
                'createStageInstance' => ['method' => HttpMethod::Post, 'path' => '/stage-instances'],
                'getStageInstance' => ['method' => HttpMethod::Get, 'path' => '/stage-instances/{channel_id}'],
                'modifyStageInstance' => ['method' => HttpMethod::Patch, 'path' => '/stage-instances/{channel_id}'],
                'deleteStageInstance' => ['method' => HttpMethod::Delete, 'path' => '/stage-instances/{channel_id}'],
            ],
            'stickers' => [
                'getSticker' => ['method' => HttpMethod::Get, 'path' => '/stickers/{sticker_id}'],
                'listNitroStickerPacks' => ['method' => HttpMethod::Get, 'path' => '/sticker-packs'],
                'listGuildStickers' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/stickers'],
                'getGuildStickers' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/stickers'],
                'getGuildSticker' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/stickers/{sticker_id}'],
                'createGuildSticker' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/stickers'],
                'modifyGuildSticker' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/stickers/{sticker_id}'],
                'deleteGuildSticker' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/stickers/{sticker_id}'],
            ],
            'templates' => [
                'getGuildTemplate' => ['method' => HttpMethod::Get, 'path' => '/guilds/templates/{template_code}'],
                'createGuildFromTemplate' => ['method' => HttpMethod::Post, 'path' => '/guilds/templates/{template_code}'],
                'getGuildTemplates' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/templates'],
                'createGuildTemplate' => ['method' => HttpMethod::Post, 'path' => '/guilds/{guild_id}/templates'],
                'syncGuildTemplate' => ['method' => HttpMethod::Put, 'path' => '/guilds/{guild_id}/templates/{template_code}'],
                'modifyGuildTemplate' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/templates/{template_code}'],
                'deleteGuildTemplate' => ['method' => HttpMethod::Delete, 'path' => '/guilds/{guild_id}/templates/{template_code}'],
            ],
            'users' => [
                'getCurrentUser' => ['method' => HttpMethod::Get, 'path' => '/users/@me'],
                'getUser' => ['method' => HttpMethod::Get, 'path' => '/users/{user_id}'],
                'modifyCurrentUser' => ['method' => HttpMethod::Patch, 'path' => '/users/@me'],
                'getCurrentUserGuilds' => ['method' => HttpMethod::Get, 'path' => '/users/@me/guilds'],
                'getCurrentUserGuildMember' => ['method' => HttpMethod::Get, 'path' => '/users/@me/guilds/{guild_id}/member'],
                'leaveGuild' => ['method' => HttpMethod::Delete, 'path' => '/users/@me/guilds/{guild_id}'],
                'createDm' => ['method' => HttpMethod::Post, 'path' => '/users/@me/channels'],
                'createGroupDm' => ['method' => HttpMethod::Post, 'path' => '/users/@me/channels'],
                'getUserConnections' => ['method' => HttpMethod::Get, 'path' => '/users/@me/connections'],
            ],
            'voice' => [
                'getGuildVoiceRegions' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/regions'],
                'modifyCurrentUserVoiceState' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/voice-states/@me'],
                'modifyUserVoiceState' => ['method' => HttpMethod::Patch, 'path' => '/guilds/{guild_id}/voice-states/{user_id}'],
                'listVoiceRegions' => ['method' => HttpMethod::Get, 'path' => '/voice/regions'],
            ],
            'webhooks' => [
                'createWebhook' => ['method' => HttpMethod::Post, 'path' => '/channels/{channel_id}/webhooks'],
                'getChannelWebhooks' => ['method' => HttpMethod::Get, 'path' => '/channels/{channel_id}/webhooks'],
                'getGuildWebhooks' => ['method' => HttpMethod::Get, 'path' => '/guilds/{guild_id}/webhooks'],
                'getWebhook' => ['method' => HttpMethod::Get, 'path' => '/webhooks/{webhook_id}'],
                'getWebhookWithToken' => ['method' => HttpMethod::Get, 'path' => '/webhooks/{webhook_id}/{webhook_token}', 'auth' => AuthenticationRequirement::None],
                'modifyWebhook' => ['method' => HttpMethod::Patch, 'path' => '/webhooks/{webhook_id}'],
                'modifyWebhookWithToken' => ['method' => HttpMethod::Patch, 'path' => '/webhooks/{webhook_id}/{webhook_token}', 'auth' => AuthenticationRequirement::None],
                'deleteWebhook' => ['method' => HttpMethod::Delete, 'path' => '/webhooks/{webhook_id}'],
                'deleteWebhookWithToken' => ['method' => HttpMethod::Delete, 'path' => '/webhooks/{webhook_id}/{webhook_token}', 'auth' => AuthenticationRequirement::None],
                'executeWebhook' => ['method' => HttpMethod::Post, 'path' => '/webhooks/{webhook_id}/{webhook_token}', 'auth' => AuthenticationRequirement::None],
                'executeSlackCompatibleWebhook' => ['method' => HttpMethod::Post, 'path' => '/webhooks/{webhook_id}/{webhook_token}/slack', 'auth' => AuthenticationRequirement::None],
                'executeGitHubCompatibleWebhook' => ['method' => HttpMethod::Post, 'path' => '/webhooks/{webhook_id}/{webhook_token}/github', 'auth' => AuthenticationRequirement::None],
            ],
        ];
    }
}
