<?php

declare(strict_types=1);

namespace Kyzegs\Laracord;

use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Promise\Utils;
use GuzzleHttp\RequestOptions;
use Illuminate\Contracts\Config\Repository;
use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Support\Sleep;
use Illuminate\Support\Str;
use Kyzegs\GuzzleRateLimitMiddleware\Exception\InvalidRequestLimitExceededException;
use Kyzegs\GuzzleRateLimitMiddleware\Exception\RateLimitDelayExceededException;
use Kyzegs\GuzzleRateLimitMiddleware\Exception\RateLimitExceededException;
use Kyzegs\Laracord\Contracts\Client;
use Kyzegs\Laracord\Endpoints\EndpointCatalog;
use Kyzegs\Laracord\Enums\AuthenticationRequirement;
use Kyzegs\Laracord\Events\RequestFailed;
use Kyzegs\Laracord\Events\RequestSending;
use Kyzegs\Laracord\Events\ResponseReceived;
use Kyzegs\Laracord\Exceptions\DiscordAuthenticationException;
use Kyzegs\Laracord\Exceptions\DiscordForbiddenException;
use Kyzegs\Laracord\Exceptions\DiscordHttpException;
use Kyzegs\Laracord\Exceptions\DiscordInvalidRequestLimitException;
use Kyzegs\Laracord\Exceptions\DiscordNotFoundException;
use Kyzegs\Laracord\Exceptions\DiscordRateLimitException;
use Kyzegs\Laracord\Exceptions\DiscordServerException;
use Kyzegs\Laracord\Exceptions\DiscordTransportException;
use Kyzegs\Laracord\Exceptions\MissingAuthenticationException;
use Kyzegs\Laracord\Http\DiscordRequest;
use Kyzegs\Laracord\Http\DiscordResponse;
use Kyzegs\Laracord\Pool\Pool;
use Kyzegs\Laracord\Resources\ResourceClient;
use Kyzegs\Laracord\ValueObjects\AuditLogReason;
use Kyzegs\Laracord\ValueObjects\Authentication;
use Kyzegs\Laracord\ValueObjects\OAuthAccessToken;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamInterface;

/**
 * Resource accessors (generated by bin/resources.php).
 *
 * @method \Kyzegs\Laracord\Resources\Generated\ApplicationsResource applications()
 * @method \Kyzegs\Laracord\Resources\Generated\AuditLogsResource auditLogs()
 * @method \Kyzegs\Laracord\Resources\Generated\AutoModerationResource autoModeration()
 * @method \Kyzegs\Laracord\Resources\Generated\ChannelsResource channels()
 * @method \Kyzegs\Laracord\Resources\Generated\CommandsResource commands()
 * @method \Kyzegs\Laracord\Resources\Generated\EmojisResource emojis()
 * @method \Kyzegs\Laracord\Resources\Generated\EntitlementsResource entitlements()
 * @method \Kyzegs\Laracord\Resources\Generated\GuildsResource guilds()
 * @method \Kyzegs\Laracord\Resources\Generated\InteractionsResource interactions()
 * @method \Kyzegs\Laracord\Resources\Generated\InvitesResource invites()
 * @method \Kyzegs\Laracord\Resources\Generated\LobbiesResource lobbies()
 * @method \Kyzegs\Laracord\Resources\Generated\MessagesResource messages()
 * @method \Kyzegs\Laracord\Resources\Generated\Oauth2Resource oauth2()
 * @method \Kyzegs\Laracord\Resources\Generated\PollsResource polls()
 * @method \Kyzegs\Laracord\Resources\Generated\RoleConnectionsResource roleConnections()
 * @method \Kyzegs\Laracord\Resources\Generated\ScheduledEventsResource scheduledEvents()
 * @method \Kyzegs\Laracord\Resources\Generated\SkusResource skus()
 * @method \Kyzegs\Laracord\Resources\Generated\SoundboardsResource soundboards()
 * @method \Kyzegs\Laracord\Resources\Generated\StagesResource stages()
 * @method \Kyzegs\Laracord\Resources\Generated\StickersResource stickers()
 * @method \Kyzegs\Laracord\Resources\Generated\SubscriptionsResource subscriptions()
 * @method \Kyzegs\Laracord\Resources\Generated\TemplatesResource templates()
 * @method \Kyzegs\Laracord\Resources\Generated\UsersResource users()
 * @method \Kyzegs\Laracord\Resources\Generated\VoiceResource voice()
 * @method \Kyzegs\Laracord\Resources\Generated\WebhooksResource webhooks()
 */
final readonly class DiscordClient implements Client
{
    public function __construct(
        private ClientFactory $clientFactory,
        private ClientInterface $client,
        private Authentication $authentication,
        private Repository $repository,
        private Dispatcher $events,
    ) {}

    public function asBot(?string $token = null): self
    {
        return $this->clientFactory->make(Authentication::bot($token ?? (string) $this->repository->get('laracord.bot_token', '')));
    }

    public function asUser(string|OAuthAccessToken $token): self
    {
        return $this->clientFactory->make(Authentication::bearer($token));
    }

    public function withoutAuthentication(): self
    {
        return $this->clientFactory->make(Authentication::none());
    }

    public function resource(string $name): ResourceClient
    {
        $class = sprintf('%s\\Resources\\Generated\\%sResource', __NAMESPACE__, Str::studly($name));

        if (class_exists($class) && is_subclass_of($class, ResourceClient::class)) {
            return new $class($this, $name);
        }

        return new ResourceClient($this, $name);
    }

    /** @param array<int, mixed> $arguments */
    public function __call(string $name, array $arguments): ResourceClient
    {
        if ($arguments === [] && EndpointCatalog::hasResource($name)) {
            return $this->resource($name);
        }

        throw new \BadMethodCallException('Unknown Discord resource '.$name.'.');
    }

    public function send(DiscordRequest $discordRequest): DiscordResponse
    {
        [$method, $path, $options] = $this->prepare($discordRequest);
        $requestId = (string) Str::uuid();
        $startedAt = microtime(true);

        $this->events->dispatch(new RequestSending($discordRequest, $requestId));

        $attempts = max(1, (int) $this->repository->get('laracord.http.server_retries', 5));
        $response = null;
        for ($attempt = 0; $attempt < $attempts; $attempt++) {
            try {
                $response = $this->client->request($method, $path, $options);
            } catch (\Throwable $exception) {
                if ($exception instanceof ConnectException && $attempt < $attempts - 1) {
                    Sleep::usleep((1 + $attempt * 2) * 1_000_000);
                    $this->rewindMultipart($options[RequestOptions::MULTIPART] ?? []);

                    continue;
                }

                throw $this->fail($discordRequest, $this->classify($exception), $requestId, $startedAt, $attempt + 1);
            }

            if (! in_array($response->getStatusCode(), [500, 502, 504, 524], true) || $attempt === $attempts - 1) {
                break;
            }

            Sleep::usleep((1 + $attempt * 2) * 1_000_000);
            $this->rewindMultipart($options[RequestOptions::MULTIPART] ?? []);
        }

        if (! $response instanceof ResponseInterface) {
            throw $this->fail($discordRequest, new DiscordTransportException('Discord request completed without a response.'), $requestId, $startedAt, $attempt + 1);
        }

        try {
            $discordResponse = $this->makeResponse($discordRequest, $response);
        } catch (\Throwable $throwable) {
            throw $this->fail($discordRequest, $throwable, $requestId, $startedAt, $attempt + 1);
        }

        $this->events->dispatch(new ResponseReceived($discordRequest, $discordResponse, $requestId, $this->elapsed($startedAt), $attempt + 1));

        return $discordResponse;
    }

    /**
     * Send multiple requests concurrently. The callback receives a Pool to build
     * requests; the returned array's keys are preserved, and each value becomes a
     * DiscordResponse or the Throwable the request failed with. Pooled requests
     * bypass the server-error retry loop.
     *
     * @param  callable(Pool): array<array-key, DiscordRequest>  $callback
     * @return array<array-key, DiscordResponse|\Throwable>
     */
    public function pool(callable $callback): array
    {
        $requests = $callback(new Pool);

        $promises = [];
        $completedAt = [];
        $requestIds = [];
        $startedAt = [];
        foreach ($requests as $key => $discordRequest) {
            [$method, $path, $options] = $this->prepare($discordRequest);
            $requestIds[$key] = (string) Str::uuid();
            $startedAt[$key] = microtime(true);
            $options[RequestOptions::ON_STATS] = static function () use (&$completedAt, $key): void {
                $completedAt[$key] = microtime(true);
            };
            $this->events->dispatch(new RequestSending($discordRequest, $requestIds[$key]));
            $promises[$key] = $this->client->requestAsync($method, $path, $options);
        }

        $results = [];
        foreach (Utils::settle($promises)->wait() as $key => $settled) {
            $discordRequest = $requests[$key];

            if ($settled['state'] === 'fulfilled') {
                try {
                    $discordResponse = $this->makeResponse($discordRequest, $settled['value']);
                    $this->events->dispatch(new ResponseReceived($discordRequest, $discordResponse, $requestIds[$key], $this->elapsed($startedAt[$key], $completedAt[$key] ?? null)));
                    $results[$key] = $discordResponse;
                } catch (\Throwable $exception) {
                    $results[$key] = $this->fail($discordRequest, $exception, $requestIds[$key], $startedAt[$key], completedAt: $completedAt[$key] ?? null);
                }

                continue;
            }

            $results[$key] = $this->fail($discordRequest, $this->classify($settled['reason']), $requestIds[$key], $startedAt[$key], completedAt: $completedAt[$key] ?? null);
        }

        return $results;
    }

    /**
     * Build the Guzzle method, path, and options for a request.
     *
     * @return array{0: string, 1: string, 2: array<string, mixed>}
     */
    private function prepare(DiscordRequest $discordRequest): array
    {
        $header = $this->authentication->header();
        if ($discordRequest->authentication === AuthenticationRequirement::REQUIRED && $header === null) {
            throw new MissingAuthenticationException('Discord endpoint requires bot or bearer authentication.');
        }

        $options = [RequestOptions::HTTP_ERRORS => false];
        if ($discordRequest->authentication !== AuthenticationRequirement::NONE && $header !== null) {
            $options[RequestOptions::HEADERS]['Authorization'] = $header;
        }

        if ($discordRequest->reason instanceof AuditLogReason) {
            $options[RequestOptions::HEADERS]['X-Audit-Log-Reason'] = rawurlencode((string) $discordRequest->reason);
        }

        $path = ltrim($discordRequest->resolvedPath(), '/').$this->queryString($discordRequest->query);
        $body = $discordRequest->bodyArray();
        if ($discordRequest->files !== []) {
            $multipart = [];
            if ($body !== null) {
                $multipart[] = ['name' => 'payload_json', 'contents' => json_encode($body, JSON_THROW_ON_ERROR)];
            }

            foreach ($discordRequest->files as $index => $file) {
                $part = [
                    'name' => (string) ($file['name'] ?? 'files['.$index.']'),
                    'contents' => $file['contents'],
                ];
                if (isset($file['filename'])) {
                    $part['filename'] = $file['filename'];
                }

                if (isset($file['content_type'])) {
                    $part['headers'] = ['Content-Type' => $file['content_type']];
                }

                $multipart[] = $part;
            }

            $options[RequestOptions::MULTIPART] = $multipart;
        } elseif ($body !== null) {
            $options[$discordRequest->form ? RequestOptions::FORM_PARAMS : RequestOptions::JSON] = $body;
        }

        return [$discordRequest->method->value, $path, $options];
    }

    /** Map a low-level transport exception to its Discord equivalent. */
    private function classify(\Throwable $exception): \Throwable
    {
        return match (true) {
            $exception instanceof InvalidRequestLimitExceededException => new DiscordInvalidRequestLimitException($exception->retryAfter, previous: $exception),
            $exception instanceof RateLimitDelayExceededException => new DiscordRateLimitException($exception->retryAfter, previous: $exception),
            $exception instanceof RateLimitExceededException => new DiscordRateLimitException($exception->getRetryAfter(), $exception->isGlobal(), $exception),
            $exception instanceof ConnectException => new DiscordTransportException($exception->getMessage(), $exception->getCode(), previous: $exception),
            default => $exception,
        };
    }

    /** Turn a received response into a DiscordResponse, throwing for non-2xx statuses. */
    private function makeResponse(DiscordRequest $discordRequest, ResponseInterface $response): DiscordResponse
    {
        $contents = (string) $response->getBody();
        $discordResponse = new DiscordResponse($response, $contents);
        if ($response->getStatusCode() >= 200 && $response->getStatusCode() < 300) {
            return $discordResponse;
        }

        throw match ($response->getStatusCode()) {
            401 => new DiscordAuthenticationException($discordResponse, $discordRequest),
            403 => new DiscordForbiddenException($discordResponse, $discordRequest),
            404 => new DiscordNotFoundException($discordResponse, $discordRequest),
            500, 502, 504, 524 => new DiscordServerException($discordResponse, $discordRequest),
            default => new DiscordHttpException($discordResponse, $discordRequest),
        };
    }

    /** Dispatch the failure event and return the exception so callers can throw or collect it. */
    private function fail(DiscordRequest $discordRequest, \Throwable $exception, string $requestId, float $startedAt, int $attempts = 1, ?float $completedAt = null): \Throwable
    {
        $this->events->dispatch(new RequestFailed($discordRequest, $exception, $requestId, $this->elapsed($startedAt, $completedAt), $attempts));

        return $exception;
    }

    private function elapsed(float $startedAt, ?float $completedAt = null): float
    {
        return (($completedAt ?? microtime(true)) - $startedAt) * 1000;
    }

    /** @param array<string, mixed> $query */
    private function queryString(array $query): string
    {
        $parts = [];
        foreach ($query as $key => $value) {
            foreach (is_array($value) ? $value : [$value] as $item) {
                $item = is_bool($item) ? ($item ? 'true' : 'false') : $item;
                if ($item !== null) {
                    $parts[] = rawurlencode((string) $key).'='.rawurlencode((string) $item);
                }
            }
        }

        return $parts === [] ? '' : '?'.implode('&', $parts);
    }

    /** @param list<array<string, mixed>> $multipart */
    private function rewindMultipart(array $multipart): void
    {
        foreach ($multipart as $part) {
            if (is_resource($part['contents'] ?? null)) {
                rewind($part['contents']);
            } elseif (($part['contents'] ?? null) instanceof StreamInterface && $part['contents']->isSeekable()) {
                $part['contents']->rewind();
            }
        }
    }
}
